name: test_filename_lint
description: Simple lint to detect incorrectly names test files
version: 0.1.0
repository: https://github.com/pawelsa/test_filename_lint

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  analyzer: ^7.3.0
  custom_lint_builder: ^0.7.5

dev_dependencies:
  custom_lint: ^0.7.5
  lints: ^5.1.1
  test: ^1.24.0
