name: test_filename_lint
description: Simple lint to detect incorrectly names test files
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  collection: 1.19.0
  equatable: 2.0.5
  analyzer: 7.3.0
  custom_lint_builder: 0.7.5
  meta: 1.16.0

dev_dependencies:
  custom_lint: 0.7.5
  lints: 5.1.1
  test: ^1.24.0
